apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.SECRET_NAME }}-auth
data:
  IMMICH_URL: {{ .Values.IMMICH_URL | b64enc }}
  IMMICH_API: {{ .Values.IMMICH_API | b64enc }}
  RESTART_TIMEOUT: {{ str .Values.RESTART_TIMEOUT | b64enc }}